### ISSUE TITLE
Decryption takes >500 ms

### ISSUE THREAD

**Issue by PrasadGS** [jim-b/ECCSI-SAKKE#1]
Hi,

Decryption takes ~500 ms, encryption is pretty fast though. 
Has anyone faced same issue with Decryption and found the reason?

Regards,
PrasadGS

**Comment by jim-b** [comment]
On my setup getting an average of ~400ms. 

It is following the spec so it takes what it takes. 

Also, when used with encrypted voice calls (its intent) any setup delays are in 'Human time' so 1/2 second in the call setup shouldn't be that much of an issue.  

Closing.
